import { Snowflake, Thermometer, TriangleAlert } from 'lucide-react';

export type VaccineProfile = { id: string; vaccine: string; type: string; band: string; budget: string; warning: string; tone: string; batch: string; inventory: number };
export const profiles: VaccineProfile[] = [
  { id: 'engerix', vaccine: 'Engerix-B', type: 'Hepatitis B', band: '2°C — 8°C', budget: '120 min', warning: 'Freeze-sensitive: lock below 0.5°C', tone: 'cyan', batch: 'EMAA-HEPB-2409', inventory: 120 },
  { id: 'flucelvax', vaccine: 'Flucelvax', type: 'Influenza', band: '2°C — 8°C', budget: '180 min', warning: 'Freeze-sensitive: lock below 1°C', tone: 'cyan', batch: 'EMAA-FLU-2410', inventory: 80 },
  { id: 'rabavert', vaccine: 'RabAvert', type: 'Rabies PCEC', band: '2°C — 8°C', budget: '90 min', warning: 'Freeze-sensitive: lock below 0°C', tone: 'cyan', batch: 'EMAA-RAB-2411', inventory: 40 },
  { id: 'mmr', vaccine: 'M-M-R II', type: 'Measles, Mumps, Rubella', band: '-25°C — -15°C', budget: '60 min', warning: 'Deep-frozen profile', tone: 'blue', batch: 'EMAA-MMR-2412', inventory: 60 },
  { id: 'comirnaty', vaccine: 'Comirnaty', type: 'mRNA COVID-19', band: '-80°C — -60°C', budget: '30 min', warning: 'Ultra-cold: heat critical above -50°C', tone: 'violet', batch: 'EMAA-COM-2413', inventory: 30 },
  { id: 'ervebo', vaccine: 'Ervebo', type: 'Ebola Zaire Live', band: '-85°C — -65°C', budget: '25 min', warning: 'Ultra-cold profile', tone: 'violet', batch: 'EMAA-ERV-2414', inventory: 20 },
];

export function VaccineProfiles({ selectedId, onSelect, locked = false }: { selectedId?: string; onSelect?: (profile: VaccineProfile) => void; locked?: boolean }) {
  return <section className="rounded-2xl border border-slate-700/60 bg-slate-900/80 p-4"><div className="mb-4 flex items-start gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-500/15 text-violet-300"><Snowflake className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet-300">Stability matrix</p><h2 className="text-base font-semibold text-white">Select active vaccine batch</h2><p className="text-xs text-slate-500">{locked ? 'Batch selection is locked after dispatch verification.' : 'Choose the batch before its dispatch QR scan.'}</p></div></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{profiles.map((profile) => <button key={profile.id} disabled={locked} onClick={() => onSelect?.(profile)} className={`rounded-xl border bg-slate-950/35 p-3 text-left transition-colors hover:border-cyan-500/60 disabled:cursor-not-allowed disabled:opacity-65 ${selectedId === profile.id ? 'border-cyan-500 bg-cyan-950/25 ring-1 ring-cyan-500/40' : 'border-slate-700/50'}`}><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-100">{profile.vaccine}</h3><p className="text-xs text-slate-500">{profile.type}</p></div><Thermometer className={`h-4 w-4 ${profile.tone === 'violet' ? 'text-violet-300' : 'text-cyan-300'}`} /></div><div className="mt-3 flex justify-between text-xs"><span className="text-slate-500">Storage</span><span className="font-medium text-cyan-200">{profile.band}</span></div><div className="mt-1 flex justify-between text-xs"><span className="text-slate-500">Batch</span><span className="font-mono text-slate-300">{profile.batch}</span></div><div className="mt-1 flex justify-between text-xs"><span className="text-slate-500">Shipment</span><span className="font-mono text-slate-300">{profile.inventory} vials</span></div><p className="mt-2 flex gap-1 text-[11px] leading-4 text-amber-200"><TriangleAlert className="mt-0.5 h-3 w-3 shrink-0" />{profile.warning}</p></button>)}</div></section>;
}
