import { ExternalLink, Snowflake } from 'lucide-react';

export type VaccineProfile = { id: string; vaccine: string; type: string; band: string; budget: string; warning: string; tone: string; batch: string; inventory: number };
export const profiles: VaccineProfile[] = [
  { id: 'engerix', vaccine: 'Engerix-B', type: 'Hepatitis B', band: '2°C — 8°C', budget: '120 min', warning: 'Freeze-sensitive: lock below 0.5°C', tone: 'cyan', batch: 'EMAA-HEPB-2409', inventory: 120 },
  { id: 'flucelvax', vaccine: 'Flucelvax', type: 'Influenza', band: '2°C — 8°C', budget: '180 min', warning: 'Freeze-sensitive: lock below 1°C', tone: 'cyan', batch: 'EMAA-FLU-2410', inventory: 80 },
  { id: 'rabavert', vaccine: 'RabAvert', type: 'Rabies PCEC', band: '2°C — 8°C', budget: '90 min', warning: 'Freeze-sensitive: lock below 0°C', tone: 'cyan', batch: 'EMAA-RAB-2411', inventory: 40 },
  { id: 'mmr', vaccine: 'M-M-R II', type: 'Measles, Mumps, Rubella', band: '-25°C — -15°C', budget: '60 min', warning: 'Deep-frozen profile', tone: 'blue', batch: 'EMAA-MMR-2412', inventory: 60 },
  { id: 'comirnaty', vaccine: 'Comirnaty', type: 'mRNA COVID-19', band: '-80°C — -60°C', budget: '30 min', warning: 'Ultra-cold: heat critical above -50°C', tone: 'violet', batch: 'EMAA-COM-2413', inventory: 30 },
  { id: 'ervebo', vaccine: 'Ervebo', type: 'Ebola Zaire Live', band: '-85°C — -65°C', budget: '25 min', warning: 'Ultra-cold profile', tone: 'violet', batch: 'EMAA-ERV-2414', inventory: 20 },
];

export function VaccineProfiles({ selectedId, onSelect, locked = false }: { selectedId?: string; onSelect?: (profile: VaccineProfile) => void; locked?: boolean }) {
  return <section className="rounded-2xl border border-slate-700/60 bg-slate-900/80 p-4"><div className="flex items-start justify-between gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-500/15 text-violet-300"><Snowflake className="h-5 w-5" /></div><div className="flex-1"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet-300">Shipment selection</p><h2 className="text-base font-semibold text-white">Active vaccine batch</h2><p className="text-xs text-slate-500">{locked ? 'Batch selection is locked after dispatch verification.' : 'Choose the batch before its dispatch QR scan.'}</p></div><a href="https://cold-chain-shield.preview.emergentagent.com/" target="_blank" rel="noreferrer" className="flex shrink-0 items-center gap-1 rounded-lg border border-slate-700 bg-slate-800 px-2.5 py-2 text-xs font-medium text-cyan-300 hover:bg-slate-700"><ExternalLink className="h-3.5 w-3.5" /> Full details</a></div><select disabled={locked} value={selectedId} onChange={(event) => onSelect?.(profiles.find((profile) => profile.id === event.target.value) ?? profiles[0])} className="mt-4 w-full rounded-xl border border-slate-700 bg-slate-950/60 px-3 py-3 text-sm text-white outline-none focus:border-cyan-500 disabled:cursor-not-allowed disabled:opacity-65">{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.vaccine} — {profile.batch}</option>)}</select></section>;
}
